### ISSUE TITLE
Add release documentation to combined Spring Cloud documentation

### ISSUE THREAD

**Issue by JacksonBailey** [spring-cloud/spring-cloud-release#69]
The `org.springframework.cloud:spring-cloud-dependencies` POM seems to serve the same purpose as the `io.spring.platform:platform-bom` POM (assisting with ensuring compatible transitive dependencies). I can't find any information on which versions of one work with which versions of the other. Are they meant to be used together or are they not necessarily compatible?

I see in `org.springframework.cloud:spring-cloud-dependencies` that there are a lot of exclusions and most of them look like things that are in `io.spring.platform:platform-bom` but I'm not sure if this is a "best effort" to make them work together or if it's intentional to make sure they do.

This isn't really an issue with the code (maybe the documentation though), but I didn't think this would get a good answer on Stack Overflow so I thought this was the best place to ask.

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-release/blob/master/docs/src/main/asciidoc/spring-cloud-starters.adoc#using-spring-cloud-dependencies-with-spring-io-platform

Spring Cloud is outside of the platform bom. See https://github.com/spring-io/platform/issues/232

Spring Cloud has to override things in platform because platform is behind spring cloud.

**Comment by JacksonBailey** [comment]
Ahh, okay, I see. Is the content of that Asciidoc file rendered on some webpage (like on cloud.sping.io or something) or is it only there?

**Comment by spencergibb** [comment]
It does need to be aggregated with the rest.

**Comment by JacksonBailey** [comment]
I'm closing this issue as Platform BOM is EOL.
